dist: trusty
language: cpp



script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=g++-7
  - cmake --build .
  - ./hello

env:
    - COMPILER=g++-7

addons:
  apt:
   source:
    - ubuntu-toolchain-r-test
   packages:
    - g++-7
